# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Filmlibrary/ui/templates/createformwidget.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreateForm(object):
    def setupUi(self, CreateForm):
        CreateForm.setObjectName("CreateForm")
        CreateForm.resize(640, 480)
        self.widget = QtWidgets.QWidget(CreateForm)
        self.widget.setGeometry(QtCore.QRect(20, 10, 591, 261))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 20, 0)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.diskLabel = QtWidgets.QLabel(self.widget)
        self.diskLabel.setObjectName("diskLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.diskLabel)
        self.diskInput = QtWidgets.QSpinBox(self.widget)
        self.diskInput.setMinimum(1)
        self.diskInput.setMaximum(999)
        self.diskInput.setObjectName("diskInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.diskInput)
        self.titleLabel = QtWidgets.QLabel(self.widget)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.titleLabel)
        self.titleInput = QtWidgets.QLineEdit(self.widget)
        self.titleInput.setObjectName("titleInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.titleInput)
        self.yearLabel = QtWidgets.QLabel(self.widget)
        self.yearLabel.setObjectName("yearLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.yearLabel)
        self.yearInput = QtWidgets.QLineEdit(self.widget)
        self.yearInput.setText("")
        self.yearInput.setCursorPosition(1)
        self.yearInput.setClearButtonEnabled(False)
        self.yearInput.setObjectName("yearInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.yearInput)
        self.genreLabel = QtWidgets.QLabel(self.widget)
        self.genreLabel.setObjectName("genreLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.genreLabel)
        self.genreInput = QtWidgets.QLineEdit(self.widget)
        self.genreInput.setObjectName("genreInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.genreInput)
        self.directorLabel = QtWidgets.QLabel(self.widget)
        self.directorLabel.setObjectName("directorLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.directorLabel)
        self.directorInput = QtWidgets.QLineEdit(self.widget)
        self.directorInput.setObjectName("directorInput")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.directorInput)
        self.roleLabel = QtWidgets.QLabel(self.widget)
        self.roleLabel.setObjectName("roleLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.roleLabel)
        self.roleInput = QtWidgets.QLineEdit(self.widget)
        self.roleInput.setObjectName("roleInput")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.roleInput)
        self.widget1 = QtWidgets.QWidget(CreateForm)
        self.widget1.setGeometry(QtCore.QRect(20, 280, 571, 29))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(102, 0, 261, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonSave = QtWidgets.QPushButton(self.widget1)
        self.buttonSave.setObjectName("buttonSave")
        self.horizontalLayout.addWidget(self.buttonSave)
        self.buttonCancel = QtWidgets.QPushButton(self.widget1)
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout.addWidget(self.buttonCancel)

        self.retranslateUi(CreateForm)
        QtCore.QMetaObject.connectSlotsByName(CreateForm)

    def retranslateUi(self, CreateForm):
        _translate = QtCore.QCoreApplication.translate
        CreateForm.setWindowTitle(_translate("CreateForm", "Form"))
        self.diskLabel.setText(_translate("CreateForm", "Номер диска"))
        self.titleLabel.setText(_translate("CreateForm", "Название"))
        self.yearLabel.setText(_translate("CreateForm", "Год выхода"))
        self.yearInput.setInputMask(_translate("CreateForm", "9999"))
        self.genreLabel.setText(_translate("CreateForm", "Жанр"))
        self.directorLabel.setText(_translate("CreateForm", "Режиссер"))
        self.roleLabel.setText(_translate("CreateForm", "В ролях"))
        self.buttonSave.setText(_translate("CreateForm", "Сохранить"))
        self.buttonCancel.setText(_translate("CreateForm", "Отмена"))

