# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Filmlibrary/ui/templates/searchform.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchForm(object):
    def setupUi(self, SearchForm):
        SearchForm.setObjectName("SearchForm")
        SearchForm.resize(800, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SearchForm.sizePolicy().hasHeightForWidth())
        SearchForm.setSizePolicy(sizePolicy)
        SearchForm.setMinimumSize(QtCore.QSize(800, 500))
        SearchForm.setMaximumSize(QtCore.QSize(16777215, 800))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SearchForm)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, 20, 20, 5)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.queryInput = QtWidgets.QLineEdit(SearchForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryInput.sizePolicy().hasHeightForWidth())
        self.queryInput.setSizePolicy(sizePolicy)
        self.queryInput.setMinimumSize(QtCore.QSize(0, 37))
        self.queryInput.setMaximumSize(QtCore.QSize(16777215, 37))
        self.queryInput.setStatusTip("")
        self.queryInput.setObjectName("queryInput")
        self.horizontalLayout.addWidget(self.queryInput)
        self.buttonSearch = QtWidgets.QToolButton(SearchForm)
        self.buttonSearch.setMinimumSize(QtCore.QSize(90, 37))
        self.buttonSearch.setObjectName("buttonSearch")
        self.horizontalLayout.addWidget(self.buttonSearch)
        self.buttonCancel = QtWidgets.QToolButton(SearchForm)
        self.buttonCancel.setMinimumSize(QtCore.QSize(90, 37))
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout.addWidget(self.buttonCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(20, 5, 20, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkboxDisk = QtWidgets.QCheckBox(SearchForm)
        self.checkboxDisk.setObjectName("checkboxDisk")
        self.horizontalLayout_3.addWidget(self.checkboxDisk)
        self.checkboxTitle = QtWidgets.QCheckBox(SearchForm)
        self.checkboxTitle.setObjectName("checkboxTitle")
        self.horizontalLayout_3.addWidget(self.checkboxTitle)
        self.checkboxYear = QtWidgets.QCheckBox(SearchForm)
        self.checkboxYear.setObjectName("checkboxYear")
        self.horizontalLayout_3.addWidget(self.checkboxYear)
        self.checkboxGenre = QtWidgets.QCheckBox(SearchForm)
        self.checkboxGenre.setObjectName("checkboxGenre")
        self.horizontalLayout_3.addWidget(self.checkboxGenre)
        self.checkboxDirector = QtWidgets.QCheckBox(SearchForm)
        self.checkboxDirector.setObjectName("checkboxDirector")
        self.horizontalLayout_3.addWidget(self.checkboxDirector)
        self.checkboxRole = QtWidgets.QCheckBox(SearchForm)
        self.checkboxRole.setObjectName("checkboxRole")
        self.horizontalLayout_3.addWidget(self.checkboxRole)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.result = QtWidgets.QTableWidget(SearchForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result.sizePolicy().hasHeightForWidth())
        self.result.setSizePolicy(sizePolicy)
        self.result.setMinimumSize(QtCore.QSize(600, 350))
        self.result.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.result.setTabKeyNavigation(False)
        self.result.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.result.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.result.setShowGrid(True)
        self.result.setColumnCount(7)
        self.result.setObjectName("result")
        self.result.setRowCount(0)
        self.verticalLayout.addWidget(self.result)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(SearchForm)
        QtCore.QMetaObject.connectSlotsByName(SearchForm)

    def retranslateUi(self, SearchForm):
        _translate = QtCore.QCoreApplication.translate
        SearchForm.setWindowTitle(_translate("SearchForm", "Form"))
        self.queryInput.setPlaceholderText(_translate("SearchForm", "Введите текст для поиска"))
        self.buttonSearch.setStatusTip(_translate("SearchForm", "Начать поиск"))
        self.buttonSearch.setText(_translate("SearchForm", "Найти"))
        self.buttonCancel.setStatusTip(_translate("SearchForm", "Отменить поиск и вернуться к списку фильмов"))
        self.buttonCancel.setText(_translate("SearchForm", "Отменить"))
        self.checkboxDisk.setText(_translate("SearchForm", "Номер диска"))
        self.checkboxTitle.setText(_translate("SearchForm", "Название"))
        self.checkboxYear.setText(_translate("SearchForm", "Год выхода"))
        self.checkboxGenre.setText(_translate("SearchForm", "Жанр"))
        self.checkboxDirector.setText(_translate("SearchForm", "Режиссер"))
        self.checkboxRole.setText(_translate("SearchForm", "В ролях"))
        self.result.setStatusTip(_translate("SearchForm", "Результаты поиска"))
